# Generated by Django 4.2 on 2025-11-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lang_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lang_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], default='customer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='translate_app.user')),
                ('theme_color', models.CharField(default='light', max_length=20)),
                ('website_language', models.CharField(default='vi', max_length=10)),
                ('audio_speed', models.FloatField(default=1.0)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_token', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='translate_app.user')),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.CreateModel(
            name='HistoryText',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_lang', models.ForeignKey(db_column='source_lang_code', on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_texts', to='translate_app.language')),
                ('target_lang', models.ForeignKey(db_column='target_lang_code', on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_texts', to='translate_app.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_history', to='translate_app.user')),
            ],
            options={
                'db_table': 'history_text',
            },
        ),
        migrations.CreateModel(
            name='HistoryPDF',
            fields=[
                ('pdf_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_pdf_path', models.CharField(max_length=255)),
                ('translated_pdf_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_lang', models.ForeignKey(db_column='source_lang_code', on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_pdfs', to='translate_app.language')),
                ('target_lang', models.ForeignKey(db_column='target_lang_code', on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_pdfs', to='translate_app.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_history', to='translate_app.user')),
            ],
            options={
                'db_table': 'history_pdf',
            },
        ),
        migrations.CreateModel(
            name='HistoryImage',
            fields=[
                ('ocr_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_file_path', models.CharField(max_length=255)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_lang', models.ForeignKey(db_column='source_lang_code', on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_images', to='translate_app.language')),
                ('target_lang', models.ForeignKey(db_column='target_lang_code', on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_images', to='translate_app.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_history', to='translate_app.user')),
            ],
            options={
                'db_table': 'history_image',
            },
        ),
    ]
